site_name: Machine Learning for Small Bodies in the Solar System - Supplemental Material
nav:
    - Home: index.md
    - Chapter 3: chapter3/example.ipynb
    - Chapter 4: chapter4/CNN_ex.ipynb
    - Chapter 6. Asteroid spectral classification: chapter6/Asteroid-spectral-classification-example.ipynb
    - Chapter 7. Kuiper Belt Objects: chapter7/TNO-machine-learning-example.ipynb
    - Chapter 9: chapter9/cnn_mags_production.ipynb
plugins:
    - mkdocs-jupyter
theme:
    name: readthedocs
extra_javascript:
    - https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js